apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80
  # nodeSelector: (overkilled by tolerations)
  #   hello: sara 
  tolerations:
  - key: "team"
    operator: "Equal"
    value: "kaizen"
    effect: "NoSchedule"
