apiVersion: v1
kind: PersistentVolume
metadata:
  name: task-pv-volume
  labels:
    type: local
spec:
  storageClassName: standard
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk:
    pdName: kaizen
    fsType: ext4

  # hostPath: # path on the host (on which host we deployed pods = folder in the node)
  #   path: "/mnt/data" this is not the best practice 